# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Gérard Collin
title: Future CTO
email: ger.coll@appliweb.net
website: gcollin.github.io/resume-theme

# Social links
twitter_username: COLGrar
github_username:  gcollin
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: gerard-collin
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Myself
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Gerard and I'm a enterprise architect manager.

  If you are struggling to define what digital transformation or devops would means for your company, contact me, I may be able to help.

  My career proves I'm one of the few able to combine <mark>strategic view</mark> with <mark>leadership and committment</mark> to achieve <mark>tangible results</mark> in an <mark>international context</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
