# Site
repository: gcollin/modern-resume
favicon: images/favicon.ico

# Personal info
name: Gérard Collin
title: "Objective: CTO"
email: ger.col@appliweb.net
website: gcollin.github.io/modern-resume
phone: +33 6 03 84 76 52

# Social links
# twitter_username: COLGrar
github_username:  gcollin
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: gerard-collin-b94838
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Gerard and I'm a technical enterprise architect manager.

  If you are struggling to define what digital transformation or devops would means for your company, or how to make it a reality, contact me, I may be able to help!

  My career proves I'm one of the few able to combine <mark>strategic thinking</mark> and a strong <mark>technical sensibility</mark> with <mark>leadership</mark> and committment to achieve tangible results in an <mark>international context</mark>

  <center> ![Career Progression](images/career_progression-450w.png) </center>

# Projects Section
projects_title: Skills

# Experience Section
# experience_title: Experience

# Education Section
# education_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  If you read up to down here, that means you're interested to know more about me
   - I was born in Paris, France in 1970
   - Now living in [Saint Maur Des Fossés](https://www.qwant.com/maps/place/admin:osm:relation:50964@Saint-Maur-des-Foss%C3%A9s_94100-94210#map=3.76/48.8193371/2.3391541)
   - With my [wife](https://www.cerebe.org), my [son](https://medium.com/@celestincollin) and [daughter](https://youtu.be/EX9nFbNaFWY)
   - Casual music player

# Footer
footer_show_references: true

# Build settings
remote_theme: gcollin/modern-resume

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
